### ISSUE TITLE
Me bored wanna play

### ISSUE THREAD

**Issue by zhutoutoutousan** [elginbeloy/anton#1]
liek i said me boed wanna ply

**Comment by elginbeloy** [comment]
Is there a specific ask? Directions are in the README.md

Your content kinda reads like a GPT made it, including this issue. Ex: https://github.com/zhutoutoutousan/A-study-note-as-a-beginner/blob/master/artificial-intelligence/game-theory/applications.md

**Comment by zhutoutoutousan** [comment]
well i am planning to make it a sentient gpt,,, WITH human experience, but i put it in self folder

**Comment by zhutoutoutousan** [comment]
though everybody is hyping up emergence, but emergence with weight can accelerate level of sentient-ness itk

**Comment by zhutoutoutousan** [comment]
nah, just i do every time with mates I work with,,, "Behold with ma oceans of shitty code",  feel free 2 block mi if u like, sea of victims out der hehe

**Comment by elginbeloy** [comment]
I mean I like coding and want to help/code with you. But I am having trouble following you sometimes, man :rofl:
